// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCJb7C40QbSC1Ts9hOBipurLreILiRDpcA',
    appId: '1:131486164181:web:6a40859b4dc6627cbcae5c',
    messagingSenderId: '131486164181',
    projectId: 'taskpro-42cba',
    authDomain: 'taskpro-42cba.firebaseapp.com',
    storageBucket: 'taskpro-42cba.firebasestorage.app',
    measurementId: 'G-JGJHMX4W1F',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAYwE6C2Y2ZKfLhEWabhR1NmB4kTEZ2e4M',
    appId: '1:131486164181:android:a28df73fb7b6648abcae5c',
    messagingSenderId: '131486164181',
    projectId: 'taskpro-42cba',
    storageBucket: 'taskpro-42cba.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC5hGGC4w1TokbsNX4Z2oDcG0Wvo8Zz_xg',
    appId: '1:131486164181:ios:35e608946d475baebcae5c',
    messagingSenderId: '131486164181',
    projectId: 'taskpro-42cba',
    storageBucket: 'taskpro-42cba.firebasestorage.app',
    iosBundleId: 'com.example.taskpro',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyC5hGGC4w1TokbsNX4Z2oDcG0Wvo8Zz_xg',
    appId: '1:131486164181:ios:35e608946d475baebcae5c',
    messagingSenderId: '131486164181',
    projectId: 'taskpro-42cba',
    storageBucket: 'taskpro-42cba.firebasestorage.app',
    iosBundleId: 'com.example.taskpro',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCJb7C40QbSC1Ts9hOBipurLreILiRDpcA',
    appId: '1:131486164181:web:7e2411c8978f4692bcae5c',
    messagingSenderId: '131486164181',
    projectId: 'taskpro-42cba',
    authDomain: 'taskpro-42cba.firebaseapp.com',
    storageBucket: 'taskpro-42cba.firebasestorage.app',
    measurementId: 'G-T74FXBGTZW',
  );
}
